email:
  false

dist:
  trusty

git:
  depth:
    false

env:
  global:
    - secure: "1qG2QjOUK3KvQT6YhgZmy288Q8V/OiiUeNMR/5Iac2L1QC9SGBwUWrGCLr2Yc+nrWnHnl9iKCXqqbHK0Gka2setDZMc8hHEYmw2W9MQ6cpa9/Sa8frC1e5UZo/Dsj7qlTVVn4aW0grV63qZ/WZzarPVQ3KCisj5RJPmXG8ipor8V8SUkOPGeHrgNwOeRaShjmJa5rTrnCIE5ajTijcYI+jHSSTy6SbuKGZBlc6Ut4F6wihNQZobtxic3IxGdIb3ok04ycazd0h6fjujCSGkTunF48vnHmXGGEnCcTP+tKeLUbX2m3IePVSiIpP58keYaW7fJDJCKZNAiNzU0aULXNKMVKcSNhcyzi6K02bcgHo7d/E3BNRulppzl51kSDgUI9Hpp/QA+aOQpkM7+YQQMBca4VOtMu4XomArCn2ymUFsLijCaGkXSRPkWK0+BoReeQi4VLmuEmg6+fmYD6F87rKxHciP3oQTLUIS80JbX3oNUPF7c65cNKGFNm4foe8kr+qqaEb7xhAeKlGzfpUUx4lxmPSqjW/T7R3DuFVK9aYXMBIo2cQQdWw9ocdUpVjCc+xw9QvsDONcxpfm6ZPWNsOH5Dd/a05Aed3zSa6Zh5gTszsJs8WxsCkFit2KTrv6O2gz/AZDdD6Bgb9UvvSF1vAvyhIYO8YNxwfzowqidUhw="
    - RGGEN_SAMPLE_DIRECTORY=$TRAVIS_BUILD_DIR/rggen-sample

cache:
  bundler

language:
  ruby

matrix:
  include:
    - rvm: 2.3.8
    - rvm: 2.4.9
    - rvm: 2.5.7
    - rvm: 2.6.5
    - rvm: 2.7.0

addons:
  sonarcloud:
    organization:
      rggen
    token:
      secure: "n4oPsifQ0Hsm2SUjyi+8gjnrXG3/OVSrhkVrAqo/qWdn2OGhH0jionZ7KIhZv6YAcUNbPbpaDmAKgretR9qippbyPKZc/wxeYP7kZRr+238mI5DLucUfKoMbdF7NO/mdo9CWG9LKfQT93Hi7gybL+8mOfibd8lgoAbHCRxnsq4o+lIrcWRT32hzS0x2oUJ0ToDohNhLXla2yF4wWdgyaAtHf97Epf5zJXLLcyKKgUyljAGZ3WTKdJfH7a2gbVF4iPMP84rUoQUsnjqPcqSjOadOJY6KWyprJDYP/3XjrdZ+2gQJ/bRqDyUshqt4lK2hTYPq8Q/BoSsv7hIxcY7y4zNBxJo1T61sGknt7bsKj2hFyWCALABNRSjREfP4PtszEAgX9+D9wAr1b33nAKs2DkIPegpTVYglvyxcd+2Fi5VHb3wA5lLxEDBlXkLUSkmGkFUZf4hrRBq1Ivs83s3+lcSxpV64MV9sHjrJsUCOYKlQxNy8HBx32UhLhRSkJZAPREiwez7rpzrZOkLfuMFwIE56IEb6yxr5OKV/oAJUbosWLep7A23CDuHERofYv98m2XLRb/jbNKwUmsbJIZCn1uNR0XI6eUnYXXdTivEW4AeMis4jmwO2KOVSxn8H0r5Eb3kl1S10oIZBAkYpi8QAz+0NnX7G6ENJplWOdy1rnm3M="

before_install:
  - "git clone https://github.com/rggen/rggen-sample.git"
  - "env -u RUBYOPT gem update --system"
  - "env -u RUBYOPT gem install bundler"

script:
  - bundle exec rake coverage
  - sonar-scanner
